### ISSUE TITLE
 run action  执行打卡 部分报错

### ISSUE THREAD

**Issue by missay-nine** [LinChiQ/NewWoZaiXiaoYuan#14]
Traceback (most recent call last):
  File "/home/runner/work/NewWoZaiXiaoYuan/NewWoZaiXiaoYuan/actionVersion.py", line [23](https://github.com/missay-nine/NewWoZaiXiaoYuan/actions/runs/10815483598/job/30004475541#step:5:24)2, in <module>
***账号登陆成功！
    main()
  File "/home/runner/work/NewWoZaiXiaoYuan/NewWoZaiXiaoYuan/actionVersion.py", line 216, in main
    if os.environ['dorm_sign'] == 'yes':
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'dorm_sign'
Error: Process completed with exit code 1

大佬 这是提示我 dorm_sign 不存在吗 可是我在环境变量中已经设置了  这是正常的还是不正常的

**Comment by missay-nine** [comment]
我在看看，，
