### ISSUE TITLE
action 工作流启动执行打卡模块失败 

### ISSUE THREAD

**Issue by missay-nine** [LinChiQ/NewWoZaiXiaoYuan#15]
貌似是找不到 dorm sign 变量    

 Traceback (most recent call last):
  File "/home/runner/work/NewWoZaiXiaoYuan/NewWoZaiXiaoYuan/actionVersion.py", line [23](https://github.com/missay-nine/NewWoZaiXiaoYuan/actions/runs/10815483598/job/30004475541#step:5:24)2, in <module>
***账号登陆成功！
    main()
  File "/home/runner/work/NewWoZaiXiaoYuan/NewWoZaiXiaoYuan/actionVersion.py", line 216, in main
    if os.environ['dorm_sign'] == 'yes':
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'dorm_sign'

自己排查了一下 
貌似 punch,yml 没有改 还是老版本
  env:
        school_name: ${{secrets.school_name}}
        receive_mail: ${{secrets.receive_mail}}
        mail_address: ${{secrets.mail_address}}
        mail_password: ${{secrets.mail_password}}
        mail_host: ${{secrets.mail_host}}
        punch_location: ${{secrets.punch_location}}
        wzxy_username: ${{secrets.wzxy_username}}
        wzxy_password: ${{secrets.wzxy_password}}
        punch_longitude: ${{secrets.punch_longitude}}
        punch_latitude: ${{secrets.punch_latitude}}
        sct_ftqq: ${{secrets.sct_ftqq}}

不知道对不对

**Comment by LinChiQ** [comment]
已采纳并修改，action版本更新有些时候更不上
