### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by starryshmily** [LinChiQ/NewWoZaiXiaoYuan#4]
2023-11-25T14:34:56Z a58560fb-71ad-4128-87a5-1df7f77739ad ERROR function invocation exception, error: catch a 'ImportError' exception(cannot import name 'etree' from 'lxml' (/opt/function/code/lxml/__init__.py))
Traceback (most recent call last):
File "./index.py", line 7, in handler
Start()
File "./WoZaiXiaoYuan.py", line 213, in Start
mail.send(config['receive'] , '返校成功！' , '返校成功！')
File "./yagmail/sender.py", line 157, in send
recipients, msg_strings = self.prepare_send(
File "./yagmail/sender.py", line 122, in prepare_send
msg = prepare_message(
File "./yagmail/message.py", line 140, in prepare_message
import premailer
File "./premailer/__init__.py", line 1, in <module>
from .premailer import Premailer, transform # noqa
File "./premailer/premailer.py", line 12, in <module>
from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/opt/function/code/lxml/__init__.py)
2023-11-25T14:34:56Z Finish invoke request 'a58560fb-71ad-4128-87a5-1df7f77739ad'(invoke Failed), duration: 1501.041ms, billing duration: 1502ms, memory used: 45.117MB, billing memory: 128MB, cpu used: 0.150U

**Comment by LinChiQ** [comment]
你在我仓库里面那个lxml的依赖包试试，python3.9环境

**Comment by starryshmily** [comment]
就是用的兄弟你提供的那个，还是不行

**Comment by LinChiQ** [comment]
你看看是不是版本问题，你去pypi下几个不同的看看，我这是正常的
